### ISSUE TITLE
Dynamic predicates aren't under SWI and Linux

### ISSUE THREAD

**Issue by ACleverDisguise** [LogtalkDotOrg/logtalk3#166]
```logtalk
:- object(pascals).

    :- uses(integer, [plus/3, succ/2]).

    :- public(reset/0).

    reset :-
        retractall(triangle_(_,_,_)).
    
    :- private(triangle_/3).
    :- dynamic(triangle_/3).

    :- public(triangle/2).

    triangle(N, Lines) :-
        triangle(N, _, DiffLines),
        difflist::as_list(DiffLines, Lines).

    % Shortcut with cached value if it exists.
    triangle(N, Line, DiffLines) :- triangle_(N, Line, DiffLines), !.

    triangle(N, Line, DiffLines) :-
        succ(N0, N),
        triangle(N0, Line0, DiffLines0),
        ZL = [0|Line0],
        list::append(Line0, [0], ZR),
        meta::map(plus, ZL, ZR, Line),
        difflist::add(Line, DiffLines0, DiffLines),
        asserta(triangle_(N, Line, DiffLines)).

    triangle(1, [1], [[1]|X]-X).

:- end_object.
```

The previous code, when consulted in `swilgt` and then calling `pascals::triangle(700, Ls).` occupies (as expected) an enormous amount of memory for the `swipl` process.  (Roughly 3.5GB.)  When run under Windows 10-native SWI-Prolog a subsequent call to `pascals::reset.` releases all such memory.  When run under a Linux environment (tested was an Ubuntu environment run under WSL as well as a native Linux Mint environment), the `swipl` process never releases the memory.  A subsequent call to `pascals::triangle(700, Ls).` simply builds up more memory usage atop the existing ~3.5GB, topping out at slightly over 7GB if permitted to run the full distance.

So this is a bug in the Linux implementation of `swipl`, right?

I translated the above code (roughly) to Prolog and tried.

```prolog
reset :- retractall(triangle_(_,_,_)).

:- dynamic(triangle_/3).

triangle(N, Lines) :-
    triangle(N, _, ReverseLines),
    lists:reverse(ReverseLines, Lines).

triangle(N, Line, ReverseLines) :- triangle_(N, Line, ReverseLines), !.

triangle(N, Line, ReverseLines) :-
    succ(N0, N),
    triangle(N0, Line0, ReverseLines0),
    ZL = [0|Line0],
    append(Line0, [0], ZR),
    apply:maplist(plus, ZL, ZR, Line),
    ReverseLines = [Line|ReverseLines0],
    asserta(triangle_(N, Line, ReverseLines)).

triangle(1, [1], [[1]]).

run :-
    triangle(700, Ls), writeln(Ls),
    triangle(700, Ls), writeln(Ls),
    reset.
```

When this file is consulted from a pure `swipl` invocation and `run` is executed, the memory usage climbs to ~3.5GB on the first `triangle(700, Ls).` call, stays steady on the second, and drops after the `reset.` call.  This is true also if the calls are manually entered at the toplevel.

If, however, the **Prolog** version is consulted in **`swilgt`** (via `[pascal].`) and the `run.` call is made (or manually invoked one at a time), the `reset.` call does not free memory.

**Comment by pmoura** [comment]
There isn't any Logtalk or SWI-Prolog bug here. SWI-Prolog garbage collection is invoked automatically **when necessary**. It's not expected to be triggered as soon as, in this case, clauses are retracted. For details, see:

https://www.swi-prolog.org/pldoc/man?section=gc

You can modify your `run/0` predicate to reclaim the retracted clauses immediately:

```logtalk
run :-
    triangle(700, Ls), writeln(Ls),
    triangle(700, Ls), writeln(Ls),
    reset,
    garbage_collect_clauses.
```

The perceived difference when using `swilgt` instead of `swipl` to load the plain Prolog code is due to more Prolog code being loaded when you run `swilgt`: the Logtalk compiler/runtime, which is implemented in highly portable Prolog code. That changes the conditions used by the SWI-Prolog garbage collector to decide when to act. For example, in macOS, with your original plain Prolog code, when I run:

```text
$ swilgt
...
?- [pascal].
...
? -run.
....
```

The memory usage stays at 3.56 GB for awhile. However, if I type next another goal, for example:

```text
?- listing.
...
```

Then the memory usage goes down to 104.2 MB.
