### ISSUE TITLE
wrapper does not produce useable results

### ISSUE THREAD

**Issue by unthingable** [LogtalkDotOrg/logtalk3#207]
First time using `wrapper` on a Prolog project, had a number of issues. Will document them all here.

```prolog
?- logtalk_load(wrapper(loader)).
...
true.
?- wrapper::directory(".").
...
?- wrapper::save.
```

## Strange meta predicates
When a predicate is detected as meta but does not have a corresponding `:- meta_predicate(...)` directive, the wrapper will generate it as follows:
```prolog
:- meta_predicate pure/3.

:- meta_predicate is_det/1.
```
Attempting to load this results in an error.

## Missing/unrecognized adapter built-ins
This is probably the strangest one, may be a separate issue not related to wrapper.

First, when loading the generated `loader.lgt` it complained about some swipl predicates being unavailable: `Domain error: value source_file(:,?) is not in domain meta_predicate_template`. After checking `swi` adapter code and seeing that was indeed the case, I added the following to `loader.lgt`:
```prolog
'$lgt_prolog_meta_predicate'(source_file(_, _), source_file(*, *), predicate).
'$lgt_prolog_meta_directive'(debug(_), debug(*)).
```
That made the error go away, but then it issued similar complaints about other predicates that are definitely in the adapter: `Domain error: value format(+,+,:) is not in domain meta_predicate_template`.

Copying these from `adapters/swi.pl` to `loader.lgt` exactly as is was enough to quiet these errors.

```prolog
'$lgt_prolog_meta_predicate'(format(_, _, _), format(*, *, *), predicate).
'$lgt_prolog_meta_predicate'(format(_, _), format(*, *), predicate).
'$lgt_prolog_meta_predicate'(load_files(_, _), load_files(*, *), predicate).
```

The Prolog code is definitely using adapter predicates other than those without complaints.

## `:- [foo].` directive not recognized as `use_module`
Advice says to remove them but does not suggest adding a corresponding `use_module` directive.

## Duplicate `use_module` directives
Wrapper advice and resulting .lgt files will contain duplicate `use_module` directives, e.g.
```prolog
:- use_module(library(semweb/turtle)).

:- use_module(library(semweb/turtle)).

:- use_module(library(semweb/rdf_portray)).

:- use_module(library(semweb/rdf_portray)).

:- use_module(library(clpfd)).

:- use_module(library(clpfd)).
```
Also noticed the linter will sometimes report the same warning twice, not sure if related.

## env
Logtalk 3.78.0
SWI-Prolog (threaded, 64 bits, version 9.3.2-10-gf146a507d)
MacOS 14.4.1

**Comment by pmoura** [comment]
The issue with `meta_predicate/1` directives should be fixed in https://github.com/LogtalkDotOrg/logtalk3/commit/c9db15868c2cb8cb4ae137de9d0849670db79717.

Prolog meta-predicates using the `:` meta-argument indicator are ambiguous. Logtalk allows overriding the original meta-predicate directive from the user source code without requiring changes to the backend adapter file or using internal predicates. See:

https://logtalk.org/manuals/refman/directives/meta_predicate_1.html

For example:

```logtalk
:- meta_predicate'(user:source_file(*, *)).
```

Note that the interpretation of `:- [foo].` terms depend on the backend Prolog system.  It can mean consult, reconsult, `use_module/1`, or `ensure_loaded/1`. The `[...]` syntax is a **top-level** shortcut that should never be used in source files. Unfortunately, there are plenty of bad public examples of misusing this shortcut.

Is the Prolog code that you're porting with the `wrapper`  tool publicly available?

**Comment by pmoura** [comment]
The recommendation is that `use_module/1` directives should be added/moved to the loader file and then use Logtalk (not Prolog) [`use_module/2`](https://logtalk.org/manuals/refman/directives/use_module_2.html) directives inside objects.

**Comment by unthingable** [comment]
> The `[...]` syntax is a **top-level** shortcut that should never be used in source files. Unfortunately, there are plenty of bad public examples of misusing this shortcut.

👍 I must have followed those examples (and it was so much easier to type). I did convert them all to `use_module` before rewrapping, just wanted to include that in the writeup. Perhaps that could be a linter rule.
 
> Is the Prolog code that you're porting with the `wrapper` tool publicly available?

Afraid not, it's a closed source project for the time being.
